### ISSUE TITLE
Can I do something to get a better imáge

### ISSUE THREAD

**Issue by ats3788** [mudassar-tamboli/ESP32-OV7670-WebSocket-Camera#2]
Hello 
What a great Project. 
<img width="651" alt="ov7670" src="https://user-images.githubusercontent.com/38277652/50790039-18c28c00-12be-11e9-9d40-96bcf9577eaa.png">
But My Image is reddish can I change this I Tried to tweak
REG_BLUE & REG_RED  but I did not have any success.

**Comment by shikharuniyal** [comment]
when i am compiling the code it is showing this type of error

**C:\Users\SHIKHAR\Documents\Arduino\libraries\ov7670-lib-master\main.c:3:20: fatal error: avr/io.h: No such file or directory

compilation terminated.

exit status 1
Error compiling for board WEMOS LOLIN32.**

**Comment by ats3788** [comment]
I think you have the wrong Gadget it should be ESP32

**Comment by shikharuniyal** [comment]
now it displays with esp 32 wemos lolin is

Archiving built core (caching) in: C:\DOCUME~1\user\LOCALS~1\Temp\arduino_cache_826840\core\core_esp32_esp32_lolin32_FlashFreq_80,PartitionScheme_default,UploadSpeed_921600_8581ddab28451b3d9b85bf43e01a25a9.a
Traceback (most recent call last):

  File "esptool.py", line 35, in <module>

  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module

  File "site-packages\serial\__init__.py", line 27, in <module>

  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module

  File "site-packages\serial\serialwin32.py", line 15, in <module>

  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module

  File "site-packages\serial\win32.py", line 182, in <module>

  File "ctypes\__init__.py", line 375, in __getattr__

  File "ctypes\__init__.py", line 380, in __getitem__

AttributeError: function 'CancelIoEx' not found

Failed to execute script esptool

exit status -1
Error compiling for board WEMOS LOLIN32.

**Comment by mudassar-tamboli** [comment]
> Hello
> What a great Project.
> <img alt="ov7670" width="651" src="https://user-images.githubusercontent.com/38277652/50790039-18c28c00-12be-11e9-9d40-96bcf9577eaa.png">
> But My Image is reddish can I change this I Tried to tweak
> REG_BLUE & REG_RED but I did not have any success.

function display() in canvas.htm resolves the color issue
RGB565 is converted to RGB888 format before manipulating the pixels.

If the demo code is not changed then please check your OV7670 configuration

Check below link
https://github.com/ThingPulse/minigrafx/issues/8
